# Generated by Django 5.0.1 on 2024-01-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_remove_product_times_used_remove_recipe_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times_used_in_recipe',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
